name: Publish Release package

on:
  release:
    types: [published]

jobs:
  publish-release:
    uses: eclipse-keypop/keypop-actions/.github/workflows/reusable-publish-release.yml@publish-release-v1
    secrets: inherit
